using OpenQA.Selenium;
using NUnit.Framework;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using System;


namespace MintsoftTest
{
    class Tests
    {
        static void Main()
        {
            IWebDriver driver = new ChromeDriver("C:/Drivers");
            driver.Manage().Window.Maximize();
            driver.Navigate().GoToUrl(@"https://om-test.mintsoft.co.uk/UserAccount/LogOn");
            driver.FindElement(By.Name("username")).SendKeys("John.Warehouse" + Keys.Enter);
            driver.FindElement(By.Name("password")).SendKeys("clip_ominous880");
            driver.FindElement(By.Name("RememberMe")).SendKeys(" ");
            driver.FindElement(By.Id("m_login_signin_submit")).SendKeys(" ");
            new WebDriverWait(driver, TimeSpan.FromSeconds(30)).Until(ExpectedConditions.ElementToBeClickable(By.XPath("//*[@id='m_aside_left_minimize_toggle']")));
            driver.FindElement(By.XPath("//*[@id='m_aside_left_minimize_toggle']")).Click();
            driver.FindElement(By.XPath("//*[@id='m_ver_menu']/ul/li[2]")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementToBeClickable(By.XPath("//*[@id='m_ver_menu']/ul/li[2]/div/ul/li[2]/a/span")));
            driver.FindElement(By.XPath("//*[@id='m_ver_menu']/ul/li[2]/div/ul/li[2]/a/span")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementToBeClickable(By.XPath("/html/body/div[3]/div/div[2]/div/div/div[1]/div[2]/ul/li[3]")));
            driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/div/div[1]/div[2]/ul/li[3]")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("//*[@id='m_tabs_1']/div[1]/label")));
            //driver.FindElement(By.Id("ShortName")).SendKeys(Keys.Enter);
            //new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.Id("ShortName-error")));
            //PopupWindowFinder.Show("Test 1 passed");
            var Datetime = DateTime.Now.ToString();
            driver.FindElement(By.Id("ShortName")).SendKeys("ShortName" + Datetime);
            driver.FindElement(By.Id("Name")).SendKeys("Name" + Datetime);
            driver.FindElement(By.Id("Code")).SendKeys("Code" + Datetime);
            driver.FindElement(By.Id("BrandName")).SendKeys("BrandName");
            driver.FindElement(By.Id("ContactName")).SendKeys("John Atwell");
            driver.FindElement(By.Id("ContactNumber")).SendKeys("0845 345 3300");
            driver.FindElement(By.Id("AddressLine1")).SendKeys("Charnwood Building");
            driver.FindElement(By.Id("AddressLine2")).SendKeys("Holywell Park");
            driver.FindElement(By.Id("AddressLine3")).SendKeys("Holywell Park");
            driver.FindElement(By.Id("Town")).SendKeys("Loughborough");
            driver.FindElement(By.Id("County")).SendKeys("Leicestershire");
            driver.FindElement(By.Id("Postcode")).SendKeys("LE11 3GB");
            driver.FindElement(By.Id("select2-CountryId-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("United Kingdom");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("VATNumber")).SendKeys("GB0123456789");
            driver.FindElement(By.Id("EORINumber")).SendKeys("GB9876543210");
            driver.FindElement(By.Id("NIREORINumber")).SendKeys("NI9876543210");
            driver.FindElement(By.Id("IOSSNumber")).SendKeys("IOSS76543210");
            driver.FindElement(By.Id("PPINumber")).SendKeys("PPI876543210");
            driver.FindElement(By.Id("AdditionalInfo")).SendKeys("Test Client created by Selenium");
            driver.FindElement(By.Id("ContactEmail")).SendKeys("John.Atwell@theaccessgroup.com");
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementIsVisible(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[2]/a")));
            var element = driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[2]/a"));
            Actions actions = new Actions(driver);
            actions.MoveToElement(element);
            actions.Perform();
            driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[2]/a")).Click();
            driver.FindElement(By.Id("select2-PickingCalculationType-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("PerOrderLine");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("StandardPickingCost")).Clear();
            driver.FindElement(By.Id("StandardPickingCost")).SendKeys("1.87");
            driver.FindElement(By.Id("AdditionalPickingCostPerItem")).Clear();
            driver.FindElement(By.Id("AdditionalPickingCostPerItem")).SendKeys("0.12");
            driver.FindElement(By.Id("NumberOfItemsIncludedInStandardPick")).Clear();
            driver.FindElement(By.Id("NumberOfItemsIncludedInStandardPick")).SendKeys("2");
            driver.FindElement(By.XPath("//*[@id='m_tabs_2']/div[5]/div/div")).Click();
            driver.FindElement(By.Id("StandardCartonPickingCost")).Clear();
            driver.FindElement(By.Id("StandardCartonPickingCost")).SendKeys("1.87");
            driver.FindElement(By.Id("AdditionalPickingCostPerCarton")).Clear();
            driver.FindElement(By.Id("AdditionalPickingCostPerCarton")).SendKeys("0.12");
            var element2 = driver.FindElement(By.Id("PickingSKUCost"));
            Actions actions2 = new Actions(driver);
            actions2.MoveToElement(element2);
            actions2.Perform();
            driver.FindElement(By.XPath("//*[@id='m_tabs_2']/div[8]/div/div/div")).Click();
            driver.FindElement(By.Id("StandardPalletPickingCost")).Clear();
            driver.FindElement(By.Id("StandardPalletPickingCost")).SendKeys("2.50");
            driver.FindElement(By.Id("AdditionalPickingCostPerPallet")).Clear();
            driver.FindElement(By.Id("AdditionalPickingCostPerPallet")).SendKeys("1.00");
            driver.FindElement(By.Id("StandardPalletPickingCost")).Clear();
            driver.FindElement(By.Id("StandardPalletPickingCost")).SendKeys("2.50");
            driver.FindElement(By.Id("PickingSKUCost")).Clear();
            driver.FindElement(By.Id("PickingSKUCost")).SendKeys("2.50");
            driver.FindElement(By.Id("PercentagePickingCost")).Clear();
            driver.FindElement(By.Id("PercentagePickingCost")).SendKeys("5");
            driver.FindElement(By.Id("ReturnsCostFirstItem")).Clear();
            driver.FindElement(By.Id("ReturnsCostFirstItem")).SendKeys("2.50");
            driver.FindElement(By.Id("ReturnsCostAdditionalItem")).Clear();
            driver.FindElement(By.Id("ReturnsCostAdditionalItem")).SendKeys("0.40");
            driver.FindElement(By.Id("DefaultPackagingFee")).Clear();
            driver.FindElement(By.Id("DefaultPackagingFee")).SendKeys("1.00");
            driver.FindElement(By.Id("PickingCostPerCBM")).Clear();
            driver.FindElement(By.Id("PickingCostPerCBM")).SendKeys("0.50");
            driver.FindElement(By.Id("PerOrderAdminFee")).Clear();
            driver.FindElement(By.Id("PerOrderAdminFee")).SendKeys("0.20");
            actions.MoveToElement(element);
            actions.Perform();
            driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[3]/a")).Click();
            driver.FindElement(By.Id("StockManagementFee")).Clear();
            driver.FindElement(By.Id("StockManagementFee")).SendKeys("15.20");
            driver.FindElement(By.Id("VolumetricStorageFee")).Clear();
            driver.FindElement(By.Id("VolumetricStorageFee")).SendKeys("1.80");
            driver.FindElement(By.Id("select2-VolumetricStorageFrequency-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Weekly");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("select2-StorageType-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("storageunits");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[4]/a")).Click();
            driver.FindElement(By.Id("GoodsInCostCarton")).Clear();
            driver.FindElement(By.Id("GoodsInCostCarton")).SendKeys("0.50");
            driver.FindElement(By.Id("GoodsInCostPallet")).Clear();
            driver.FindElement(By.Id("GoodsInCostPallet")).SendKeys("1.80");
            driver.FindElement(By.Id("GoodsInCost20ftContainer")).Clear();
            driver.FindElement(By.Id("GoodsInCost20ftContainer")).SendKeys("10.99");
            driver.FindElement(By.Id("GoodsInCost40ftContainer")).Clear();
            driver.FindElement(By.Id("GoodsInCost40ftContainer")).SendKeys("19.99");
            driver.FindElement(By.Id("GoodsInCost40ftContainerHC")).Clear();
            driver.FindElement(By.Id("GoodsInCost40ftContainerHC")).SendKeys("22.99");
            driver.FindElement(By.Id("GoodsInCost45ftContainer")).Clear();
            driver.FindElement(By.Id("GoodsInCost45ftContainer")).SendKeys("22.99");
            driver.FindElement(By.Id("GoodsInCost45ftContainerHC")).Clear();
            driver.FindElement(By.Id("GoodsInCost45ftContainerHC")).SendKeys("24.99");
            driver.FindElement(By.Id("GoodsInCostSku")).Clear();
            driver.FindElement(By.Id("GoodsInCostSku")).SendKeys("00.07");
            driver.FindElement(By.Id("GoodsInCostUnit")).Clear();
            driver.FindElement(By.Id("GoodsInCostUnit")).SendKeys("00.08");
            driver.FindElement(By.Id("AdminChargePerASN")).Clear();
            driver.FindElement(By.Id("AdminChargePerASN")).SendKeys("00.12");
            driver.FindElement(By.Id("HourRateChargeForASN")).Clear();
            driver.FindElement(By.Id("HourRateChargeForASN")).SendKeys("12.52");
            actions.MoveToElement(element);
            actions.Perform();
            driver.FindElement(By.XPath("/html/body/div[3]/div/div[2]/div/form/div/div[1]/div[2]/ul/li[5]/a")).Click();
            driver.FindElement(By.Id("select2-CurrencyId-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Australian Dollar");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("select2-CourierServiceTypeId-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Express");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[3]/div/div/div")).Click();
            driver.FindElement(By.Id("select2-Active-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("N");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("select2-HoldingOrderPolicyStr-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("SplitOrder");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("select2-BackOrderStockAllocationPolicyStr-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Manual");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("select2-PickingLogicType-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Batch");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[8]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[9]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[10]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[11]/div/div/div")).Click();
            driver.FindElement(By.Id("DefaultUnitStorageSize")).Clear();
            driver.FindElement(By.Id("DefaultUnitStorageSize")).SendKeys("1.5");
            driver.FindElement(By.Id("PackagingInstructions")).SendKeys("Selenium Packaging Instructions");
            driver.FindElement(By.Id("DefaultCustomsDescription")).SendKeys("Selenium Customs Description");
            driver.FindElement(By.Id("select2-CountryOfManufactureId-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("China");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.Id("DefaultCommodityCode")).SendKeys("8528 52 99 00");
            driver.FindElement(By.Id("DefaultMaterial")).SendKeys("Plastic");
            driver.FindElement(By.Id("SubscriptionDelay")).Clear();
            driver.FindElement(By.Id("SubscriptionDelay")).SendKeys("1");
            driver.FindElement(By.Id("select2-SubscriptionStartDefault-container")).Click();
            new WebDriverWait(driver, TimeSpan.FromSeconds(10)).Until(ExpectedConditions.ElementExists(By.XPath("/html/body/span/span/span[1]/input")));
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys("Startofmonth");
            driver.FindElement(By.XPath("/html/body/span/span/span[1]/input")).SendKeys(Keys.Enter);
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[20]/div/div/div")).Click();
            var element3 = driver.FindElement(By.Id("root"));
            Actions actions3 = new Actions(driver);
            actions3.MoveToElement(element3);
            actions3.Perform();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[21]/div/div/div")).Click();
            driver.FindElement(By.Id("ArchiveTime")).Clear();
            driver.FindElement(By.Id("ArchiveTime")).SendKeys("45");
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[23]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[24]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[25]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[26]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[27]/div/div/div")).Click();
            driver.FindElement(By.XPath("//*[@id='m_tabs_5']/div[28]/div/div/div")).Click();
            actions3.MoveToElement(element3);
            actions3.Perform();
            driver.FindElement(By.Name("PortalActions")).Click();
        }
    }

}